source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PencilCup_Example', :exclusive => true do
  pod "PencilCup", :path => "../"
end

target 'PencilCup_Tests', :exclusive => true do
  pod "PencilCup", :path => "../"

  
end
